#version: '2.4'
services:
  #контейнер adminer на php и apache2
  app:
    container_name: adminer
    build:
      context: ./apache2
      dockerfile: Dockerfile
#    volumes:
#      - ./apache2/apache_logs:/var/log/apache2
    depends_on:
      - db
    networks:
      - front_app
      - base_app
  #контейнер для сервера postgres просто из образа
  db:
    container_name: postgresql
    image: postgres:15.8-alpine3.20
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: p@ssw0rd
    ports:
      - '5432:5432'
    networks:
      - base_app
  #контейнер для сервера nginx просто из образа
  proxy:
    container_name: nginx
    image: nginx:1.27-alpine3.19
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./nginx/logs:/var/log/nginx/
    ports:
      - '80:81'
    networks:
      - front_app

#сети для связи контейнеров
networks:
  front_app:
    ipam:
      driver: default
      config:
        - subnet: '172.16.1.0/24'
  base_app:
    ipam:
      driver: default
      config:
        - subnet: '172.16.2.0/24'
